# 20 - Automation with Cron {#unit-20}

__Related Resources__:

| Type | Content |
| :-- | :-- |
| Screencast | [20-cron.webm](https://www.cs.montana.edu/users/sdowdle/csci351/videos/20-cron.webm)`r newLine()`[20-cron.mp4](https://www.cs.montana.edu/users/sdowdle/csci351/videos/20-cron.mp4) |
| Original Docs | [PDF](20/Thursday - 11MAR - Automation with cron - Systems Administration.pdf) - [HTML](20/cron.html) |
| Resources | -__RHEL7 System Administrators Guide__ Chapter 24, Automating System Tasks (PDF) |


## Background

- `cron` is a standard UNIX daemon that runs specified programs at scheduled times.
- `anacron` is like `cron` but is aimed at machines that aren't on all the time.
- `at` is a utility to schedule one-time tasks.
- `batch` is like at except it only runs one-time jobs when the system load is low.

## CRON Files

`crontabs` package: Provides /etc/crontab and periodic directories.

```bash
[root@dowdle ~]# cat /etc/crontab # (examine output)
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root

# For details see man 4 crontabs

# Example of job definition:
# .---------------- minute (0 - 59)
# |  .------------- hour (0 - 23)
# |  |  .---------- day of month (1 - 31)
# |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
# |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
# |  |  |  |  |
# *  *  *  *  * user-name  command to be executed
```

`cronie` package: An enhanced vixie-cron that provides cron service

```bash
[root@dowdle ~]# rpm -ql cronie # (examine output)
/etc/cron.d
/etc/cron.d/0hourly
/etc/cron.deny
/etc/pam.d/crond
/etc/sysconfig/crond
/lib/systemd/system/crond.service
/usr/bin/cronnext
/usr/bin/crontab
/usr/lib/.build-id
/usr/lib/.build-id/20
/usr/lib/.build-id/20/75713ea7f508632d8eb2af3c51ec59acc4aa52
/usr/lib/.build-id/32
/usr/lib/.build-id/32/811aea404298dee14ad8fd0b7b34cc9c001dab
/usr/lib/.build-id/f8
/usr/lib/.build-id/f8/e879a884df9d2370d9d1c14f2d2ccfa24fcf79
/usr/sbin/crond
/usr/share/doc/cronie
/usr/share/doc/cronie/AUTHORS
/usr/share/doc/cronie/ChangeLog
/usr/share/doc/cronie/README
/usr/share/licenses/cronie
/usr/share/licenses/cronie/COPYING
/usr/share/man/man1/cronnext.1.gz
/usr/share/man/man1/crontab.1.gz
/usr/share/man/man5/crontab.5.gz
/usr/share/man/man8/cron.8.gz
/usr/share/man/man8/crond.8.gz
/var/spool/cron
```

> Note: Directory that `cron` files are stored in is `/var/spool/cron`

__What is the daemon binary?__ - `usr/sbin/crond`

__The service control script?__ - `/lib/systemd/system/crond.service`

> `rpm -ql cronie | grep systemd`

__Config files?__ 

```bash
$ rpm -qc cronie
/etc/cron.d/0hourly
/etc/cron.deny
/etc/pam.d/crond
/etc/sysconfig/crond

$ rpm -qc crontabs
/etc/crontab
/etc/sysconfig/run-parts
```

__Documentation?__ - `rpm -qd cronie`

## CRON Access Control

From _crontab (1)_:

- If the __cron.allow__ file exists, then you _must be listed therein_ in order to be allowed to use this command.
- If the __cron.allow__ file does not exist but the __cron.deny__ file does exist, then you must not be listed in the __cron.deny__ file in order to use this command.
- If neither of these files exists, _only the super user_ will be allowed to use this command.

## Thus Says the Man Pages

From _crontab (5)_:

- The format of a cron command... each line has five time and date fields, followed by a user name if this is the system crontab file, followed by a command.
- Commands are executed by cron(8) when the minute, hour, and month of year fields match the current time, and at least one of the two day fields (day of month, or day of week) match the current time.
- cron(8) examines cron entries once every minute.

## CRONTAB Format

    {minute} {hour day-of-month} {month} {day-of-week} {command}

- minute: 0-59
- hour: 0-23
- day of month: 1-31
- month: 1-12 (or names)
- day of week: 0-7
  - (0 or 7 is Sun, or use names)

__Ranges__ of numbers are allowed. Ranges are two numbers separated with a hyphen. The specified range is inclusive. For example, 8-11 for an "hours" entry specifies execution at hours 8, 9, 10 and 11.

__Lists__ are allowed. A list is a set of numbers (or ranges) separated by commas.

_Examples_: "1,2,5,9", "0-4,8-12".

__Step values__ can be used in conjunction with ranges. Following a range with "<number>" specifies skips of the number's value through the range.

For example, "0-23/2" can be used in the hours field to specify command execution every other hour.

Steps are also permitted after an asterisk, so if you want to say "every two hours", just use "*/2".

__Names__ can also be used for the "month" and "day-of-week" fields.

- Use the first three letters of the particular day or month (case doesn’t matter).
- Ranges or lists of names are not allowed.

The "sixth" and last field specifies the _command_ to run.

The entire command portion of the line, up to a newline or % character, will be executed by `/bin/sh` or by the shell specified in the SHELL variable of the cronfile.

Percent-signs (_%_) in the command, unless escaped with backslash (/\), will be changed into newline characters, and all data after the first _%_ will be sent to the command as standard input.

## Using CRONTAB

- `crontab -l`: Lists your cron jobs
- `crontab -e`: Create / modify your cron jobs
- `crontab -r`: Deletes all cron jobs
- `crontab -u username -{additional-flag}`: Work with another user's crontab

__Examples__:


    */10 * * * * cd /var/yp; make 2>&1 > /dev/null;
    11 2 * * * /usr/bin/wget -O - -q -t 1 http://{some-url}

run system activity accounting tool every 10 minutes

    */10 * * * * root /usr/lib64/sa/sa1 1 1

generate a daily summary of process accounting at 23:53

    53 23 * * * root /usr/lib64/sa/sa2 -A

## Review from Logging Material

- `logwatch` is run as a cron job. What file is used?
- `logrotate` is run as a cron job. What file is used?

