# 21 - Server Apps: Email {#unit-21}

__Related Resources__:

| Type | Content |
| :-- | :-- |
| Screencast | [21-email-intro.webm](https://www.cs.montana.edu/users/sdowdle/csci351/videos/21-email-intro.webm)`r newLine()`[21-email-intro.mp4](https://www.cs.montana.edu/users/sdowdle/csci351/videos/21-email-intro.mp4) |
| Original Docs | [PDF](21/Tuesday - 16MAR - Server apps_ Email - Systems Administration.pdf) - [HTML](21/email.html) |
| Resources | -LaUSAH: Chapter 18, Electronic Mail`r newLine()`- LaUSAH: Chapter 16, DNS: The Domain Name System, MX records`r newLine()`- RHEL7 System Administators Guide, Chapter 15, Mail Servers (PDF) |

## What do you use for email?

- What is provided by your ISP?
- What is provided by MSU?
- Free services like gmail, Hotmail, Yahoo!Mail?
- What is provided by your work?

## What comprises an email system?

It used to be that you could simply install an SMTP server and you had an "email server". That is not the case any more. There are additional pieces that have been added to email over the last decade or so:

- Virus scanning ([ClamAV](http://www.clamav.net/))
- Spam scanning ([SpamAssassin](http://spamassassin.apache.org/))
- Webmail ([RoundCube](http://roundcube.net/) [[ours](https://www.cs.montana.edu/roundcubemail)])
- Mobile Access
- Collaboration tools
  - Global Addressbook
  - Calendaring
  - Documents
  - Resources
  - To-do lists
- Mailing lists? Usually done by separate software like Mailman (python-based) and Sympa (perl-based)

Also common these days are backup mailservers for redundancy and relaying mailservers that act as filtering systems.

## How email works

DNS plays a big role in the flow of email. When a `user@domain1.com` sends an email to `user@domain2.com` a lot has to be in place for it to work. `user@domain1.com`'s email client talks to its configured SMTP server which accepts the email for delivery. The SMTP server for domain1 has to look up the MX records for domain2. It then attempts to connect to the server with the lowest MX record value in an attempt to deliver it. If for whatever reason it can't deliver it to the first MX server, it will progress to the next MX IP with the lowest value. If all MX servers are unreachable, the SMTP server for domain1 will queue the email and try again later. Typically it tries every 4 hours for 4 days at which point it gives up.
 
- What are the MX servers for your email account?
  - To find out do the following: `dig MX yourdomain.tld`
- Does your domain have more than one MX record?
  - What are their values?

## Various anti-spam tricks

I have seen a lot of crazy stuff done by email admins to reduce their amount of spam.

- Adding MX records for servers that don't exist.
- Automatically reject every first attempt (graylisting).
- SPF and DKIM.
- Auto reject systems where you have to get put on a whitelist.
- Email is fundamentally broken and the only thing that can save it... is [PKI](http://en.wikipedia.org/wiki/Public_key_infrastructure).

## Looking for a complete package

No Linux distro I'm aware of offers a reasonable email system out of the box. Most offer some/many of the components I mentioned but none of them put them together in any integrated way. As a result a number of third party management / middleware systems have been created.

A few that seem reasonable are:

1. [Mailscanner](http://www.mailscanner.info/) ([wikipedia](http://en.wikipedia.org/wiki/Mailscanner))
2. [Zimbra Collaboration Suite](http://www.zimbra.com/) ([wikipedia](http://en.wikipedia.org/wiki/Zimbra)) [[ours](https://mail.cs.montana.edu/)]
3. [Zarafa](http://www.zarafa.com/) ([wikipedia](http://en.wikipedia.org/wiki/Zarafa_%28software%29))
4. [Scalix](http://www.scalix.com/) ([wikipedia](http://en.wikipedia.org/wiki/Scalix))
5. [Citadel](http://www.citadel.org/) ([wikipedia](http://en.wikipedia.org/wiki/Citadel/UX))
6. [Kolab](http://www.kolab.org/) ([wikipedia](https://en.wikipedia.org/wiki/Kolab))

## SMTP server software

- sendmail
- __postfix (installed in our student VMs)__
- exim
- qmail

Things SMTP servers need to be able to do:

- Host multiple domains (virtual hosting)
- Allow for `user1@domain1` and `user1@domain2` (virtual users)
- Map multiple addresses to a single account (aliases)

## POP and IMAP

- Dovecot
- UW imap
- Courier

## Email Client Programs

- `/usr/bin/mail`: Provided by the mailx  program.
  - Very simple, line oriented client
- `alpine` - Full-featured TUI client available in EPEL

## Email Related Configs

- `/etc/aliases`: global aliases and forwards
- `~/.foward`: user defined aliases and forwards
- `/etc/postfix/*`: postfix config location
  - since student VMs have Postfix installed

