--- 
title: "CSCI-351 System Administration"
subtitle: "Montana State University" 
# author: "Yihui Xie"
date: "Spring 2021" #"`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib] #, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Course Contents CSCI 351"
---

# Welcome

## Course Schedual

### Week 1

__Lectures__

- [Introduction](#unit-01)
- [History - Unix, Free Software and Linux](#unit-02)
- [What is a Linux Distribution](#unit-03)
- [What is a System Administrator](#unit-04)

__Readings__

- __TLCL__
  - [Ch.1 What is the Shell? - Ch.2 Navigation](assets/weekly-readings/week1/TLCL-week1.pdf)
- [The Daemon, the GNU, and the Penguin](assets/weekly-readings/week1/The_Daemon_the_GNU_and_the_Penguin.pdf)

### Week 2

__Lectures__

- [Installing Linux](#unit-05)
- [CLI Use](#util-06)

__Readings__

- __TLCL__
  - [Ch.3 Exploring the System](assets/weekly-readings/week2/TLCL-week2.pdf)

### Week 3

__Lectures__

- [User Accounts](#unit-07)
- [Hard disks, Partitions, and Filesystems](#unit-08)
- [Linux Filesystem Hierarchy](#unit-09)

__Readings__

- __TLCL__
  - [Ch.3 Exploring the System](assets/weekly-readings/week2/TLCL-week2.pdf)




| Course Schedual |
| :-- |
| __Week 4__ |
| - Command Line Potpourri`r newLine()`- Understanding File/Dir Ownership and Permissions |
| __Week 5__ |
| - Package Management`r newLine()`- Processes and Resource Management |
| __Week 6__ |
| - Init System & Services`r newLine()`- Backups`r newLine()`- Network Configuration |
| __Week 7__ |
| - Desktop Linux`r newLine()`- Firewalls with firewalld |
| __Week 8__ |
| MIDTERM |
| __Week 9__ |
| __Lectures__`r newLine()`- [System Logs & Monitoring](#unit-19)`r newLine()`- [Automation with CRON](#unit-20)`r newLine()`__Readings__`r newLine()`- [TLCL: 14-Package Management](assets/weekly-readings/week9/TLCL-week9.pdf)`r newLine()`- [RHEL7 - SAG, Chapter 23, Viewing and Managing Log Files](assets/weekly-readings/week9/RHEL7-SAG-Chapter-23-Viewing_and_Managing_Log_Files.pdf)`r newLine()`- [RHEL7 - SAG, Chapter 24, Automating System Tasks](assets/weekly-readings/week9/RHEL7-SAG-Chapter-24-Automating_System_Tasks.pdf)`r newLine()`__Videos__`r newLine()`- [Nerds 2.0.1](https://youtu.be/luwXqAJBneI) |




